# apprunner.yaml

# Version of the App Runner configuration schema
version: 1.0

# Services section defines the configuration for your App Runner service
services:
  - serviceName: fishdb-app
    sourceConfiguration:
      codeRepository:
        repositoryUrl: https://github.com/nithish-95/FishDBweb.git
        sourceCodeVersion:
          type: BRANCH
          value: main
        codeConfiguration:
          configurationSource: REPOSITORY
          runtime: go1
          build:
            commands:
              # Temporarily removed pre-build and post-build scripts for debugging
              build:
                - go build ./main.go ./main
            env:
              - name: MY_VAR_EXAMPLE_BUILD
                value: "build_example"
          run:
            runtime-version: 1.22.5
            command: ./main
            network:
              port: 8080
              env: APP_PORT
            env:
              - name: MY_VAR_EXAMPLE_RUN
                value: "run_example"
